name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------
    # Checkout Repo
    # -----------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    # -----------------------------
    # Setup Python
    # -----------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # -----------------------------
    # Install Dependencies
    # -----------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # -----------------------------
    # Run Unit Tests
    # -----------------------------
    - name: Run Tests
      run: pytest -q

    # -----------------------------
    # Login to Docker Hub
    # -----------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # -----------------------------
    # Build Docker Image
    # -----------------------------
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fraud-app:latest .

    # -----------------------------
    # Push Docker Image
    # -----------------------------
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fraud-app:latest

    # -----------------------------
    # Deploy to EC2
    # -----------------------------
    - name: Deploy on EC2 Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Pulling latest Docker image from Docker Hub..."

          # Login to Docker Hub on EC2
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          # Stop existing container (if exists)
          docker stop fraud-app || true
          docker rm fraud-app || true

          # Pull latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/fraud-app:latest

          echo "Running container..."

          docker run -d -p 8000:8000 --name fraud-app ${{ secrets.DOCKER_USERNAME }}/fraud-app:latest

          echo "Deployment complete!"
